nomeber = input('Digite um Numero')
print('O tipo primitivo é', type(nomeber))
print('Tem espaços?', nomeber.isspace())
print('É um número?', nomeber.isnumeric())
print('É alfabetico?', nomeber.isalpha())
print('É alfanúmerico?', nomeber.isalnum())
print('É maisculo?', nomeber.isupper())
print('É minusculo?', nomeber.islower())
print('É capitalizado?', nomeber.istitle())