Numero = float(input('Qual o número?'))
print('O numero {}, multiplicado por {}, é igual a {}'.format(Numero, 0, Numero*0))
print('O numero {}, multiplicado por {}, é igual a {}'.format(Numero, 1, Numero*1))
print('O numero {}, multiplicado por {}, é igual a {}'.format(Numero, 2, Numero*2))
print('O numero {}, multiplicado por {}, é igual a {}'.format(Numero, 3, Numero*3))
print('O numero {}, multiplicado por {}, é igual a {}'.format(Numero, 4, Numero*4))
print('O numero {}, multiplicado por {}, é igual a {}'.format(Numero, 5, Numero*5))
print('O numero {}, multiplicado por {}, é igual a {}'.format(Numero, 6, Numero*6))
print('O numero {}, multiplicado por {}, é igual a {}'.format(Numero, 7, Numero*7))
print('O numero {}, multiplicado por {}, é igual a {}'.format(Numero, 8, Numero*8))
print('O numero {}, multiplicado por {}, é igual a {}'.format(Numero, 9, Numero*9))
print('O numero {}, multiplicado por {}, é igual a {}'.format(Numero, 10, Numero*10))