N1 = int(input('Digite Um numero: '))
N2 = int(input('Digite Um numero: '))
N3 = int(input('Digite Um numero: '))
print('o maior numero é',max(N1, N2, N3))
print('o menor numero é',min(N1, N2, N3))